openapi: 3.0.1
info:
  title: McartAPI
  description: API Definition of McartAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/api
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
    delete:
      responses:
        default:
          description: Default response
  api/cartview/{id}:
    post:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
